import json
import logging
import google.generativeai as genai
from app.config import get_settings

logger = logging.getLogger(__name__)


def get_gemini_model():
    settings = get_settings()
    genai.configure(api_key=settings.gemini_api_key)
    return genai.GenerativeModel("gemini-2.5-flash")


def _mock_response() -> dict:
    """Return a fake AI result for local development (MOCK_AI=true)."""
    return {
        "title": "Mock Meeting Session",
        "summary": "This is a mock AI response. Set MOCK_AI=false and add a valid GEMINI_API_KEY to use real AI processing.",
        "sentiment": "neutral",
        "tasks": [
            {
                "title": "Configure Gemini API key",
                "description": "Add GEMINI_API_KEY to backend/.env and set MOCK_AI=false to enable real audio processing.",
                "priority": "high",
            },
            {
                "title": "Review mock session output",
                "description": "This task was auto-generated by the mock AI response. It confirms the recording pipeline is working end-to-end.",
                "priority": "low",
            },
        ],
    }


async def process_audio_with_gemini(
    audio_bytes: bytes,
    mime_type: str,
    system_prompt: str,
) -> dict:
    """
    Send audio to Gemini 2.5 Flash for transcription and structured extraction.

    Audio is processed entirely in-memory — never written to disk.
    Returns structured JSON with title, summary, sentiment, and tasks.
    """
    settings = get_settings()
    if settings.mock_ai:
        logger.info("MOCK_AI=true — skipping Gemini, returning mock response")
        return _mock_response()

    model = get_gemini_model()

    extraction_prompt = f"""{system_prompt}

Respond ONLY with valid JSON in this exact structure:
{{
  "title": "string",
  "summary": "string",
  "sentiment": "positive|neutral|negative|mixed",
  "tasks": [
    {{
      "title": "string",
      "description": "string",
      "priority": "low|medium|high|critical"
    }}
  ]
}}"""

    audio_part = {
        "mime_type": mime_type,
        "data": audio_bytes,
    }

    response = model.generate_content([extraction_prompt, audio_part])

    text = response.text.strip()
    # Strip markdown code fences if present
    if text.startswith("```"):
        text = text.split("\n", 1)[1] if "\n" in text else text[3:]
    if text.endswith("```"):
        text = text[:-3].strip()
    if text.startswith("json"):
        text = text[4:].strip()

    return json.loads(text)


DEFAULT_SYSTEM_PROMPT = """You are a meeting assistant AI. Analyze the provided audio and extract:

1. **Title**: A concise title for the meeting/session.
2. **Summary**: A brief summary of the key points discussed (2-4 sentences).
3. **Sentiment**: The overall tone of the meeting (positive, neutral, negative, mixed).
4. **Tasks**: A list of actionable tasks extracted from the discussion. For each task include:
   - title: Short, actionable task title
   - description: Detailed description of what needs to be done
   - priority: low, medium, high, or critical"""
